### ISSUE TITLE
Has version 1.2.0 already been published?

### ISSUE THREAD

**Issue by SimonSimCity** [nlhuykhang/meteor-publish-join#12]
Today, I ran `meteor npm outdated` in my repository and saw, that there is a new version - version `1.2.0` - which isn't part of this repository. Do you know anything about it? If yes, could you tag it on this repository, so I can follow along on the changes that are included there?

**EDIT:** I've installed this version and it didn't include the changes, done in `1.1.4`. In fact, it seems to be a version published after #4 was merged.

**Comment by SimonSimCity** [comment]
Please unregister the version `1.2.0` as it to me seems to be an old version that went in there accidentally.

**Comment by nlhuykhang** [comment]
Un-publish a version is a bad idea, because there might be people using it. Also I don't think you can do that anymore without contacting NPM.

I already marked the v1.2.0 as deprecated, and current version v1.1.4 has the latest tag so unless you install v1.2.0 deliberately, you will not end up using the v1.2.0.

Thank you for pointing this out.

**Comment by SimonSimCity** [comment]
Can we re-open this? Because `npm` suggests you to call `npm outdated` to check which packages are available in a newer version. On my repository it shows me the following result now:

```
Package                          Current  Wanted  Latest
meteor-publish-join                1.1.4   1.2.0   1.1.4
```

Which is correct, but it shows no-where that this package (1.2.0) is deprecated. I was wondering where this one comes from, if it at all is official, because you can't find it online, and what it was. So I installed it by hand and was wondering what so the difference could be.

To avoid this confusion another time for another person, I ask you to do something on it. I don't know how many other people follow this, but just to avoid the confusion again.

**Comment by nlhuykhang** [comment]
Sorry, I missed your last comment

The deprecated message will show up when v1.2.0 is installed explicitly. I don't know how many people are using this, therefore I can not risk un-publishing it. A little confusion is better than breaking someone's application.

**Comment by SimonSimCity** [comment]
Sorry for opening this again, but to day I just happened to run `meteor npm update` in my project and it updated the version of this package to `1.2.0` ... Do you have a suggestion of how to prevent this? Is this maybe something that would need a change on the NPM package, since it updates to a version of the package that is tagged as outdated?

**Comment by SimonSimCity** [comment]
Any idea? This issue is still present ...
