### ISSUE TITLE
Is it possible to publish result from 2 collections after manipulation

### ISSUE THREAD

**Issue by kbytin** [nlhuykhang/meteor-publish-join#20]
Is there a way to query 2 collection, manipulate with the data and publish the result?

Right now I'm publishing with JoinServer 2 queries from 2 collections and doing manipulation with the data Client Side,  but I want to send already prepared data.

**Comment by SimonSimCity** [comment]
Your publish-function could publish whatever value you want to be published to the client - just return the value and it will be available at the client using the key you published it with.

The data can easily be an array or an object which you define yourself. The examples in the readme file should give you the needed knowledge to get this working.
