### ISSUE TITLE
How can I test the outcome of a publication?

### ISSUE THREAD

**Issue by SimonSimCity** [nlhuykhang/meteor-publish-join#3]
I want to test if the outcome of my query is good. How can I do this using a test-framework?

I've tried using `johanbrook:publication-collector`, which works for https://github.com/percolatestudio/publish-counts a.o. but I couldn't get it work with your plugin ...

Writing full-app-tests seems to heavy to me, since I'm sure there's also another way ...

**Comment by nlhuykhang** [comment]
Could you reproduce the issue with `johanbrook:publication-collector` for me? A test repo would be greate

**Comment by SimonSimCity** [comment]
I see that you use `Meteor.defer()` when executing the joins. https://github.com/nlhuykhang/meteor-publish-join/blob/master/src/server/Store.js#L26

This leaves me in an odd state, because I never know when this method will finish. Instead, I'd have to wait for it. Let's give it a try.

In a PR I'm gonna push soon, I've started on an option, that you can set to the server. It will change the behavior that the function just runs once - without re-calling. This also makes it quite suitable to a functional test using `johanbrook:publication-collector`. If you want to do more complex testing, you can always start awaiting the result and go from there.

**Comment by SimonSimCity** [comment]
Fixed testing in #6
